### PR TITLE
(enhancement  #119): Generating level templates

### PR DESCRIPTION
**Pull request by kepler471**
To run this generator, select the scene `MSTDungeon.tscn` and run just that scene (F6).

It works as a standalone module, although it requires just a couple settings to be added to `project.godot`.

### CODE REVIEW

**Comment by kepler471** [comment]
I do really like the levels this produces.

image

**Comment by kepler471** [comment]
And from the red path, you could pick the most NORTH/EAST/WEST/SOUTH points ( or a variation of ) to be the entrances

**Comment by kepler471** [comment]
I think the process to get a room to run around in is: let it generate, draw our tilemap in every cell in a rectangle, then use `set_cell ( int x, int y, int tile )` with tile index = `-1` for every coordinate in `_data`, which removes a tile, and would clear out the room area.

**Comment by kepler471** [comment]
Ok just added the RandomWalker  generator, and have replace it with our Player and BearBoi.

**Comment by whitew1994WW** [comment]
Looks really good, its an impressive module tbf. The generated rooms would work really well combined with what we already have, but there may be issues with:

- spawning entrances and fitting it into the level generation that we already have (based on the current algorithm it would request a certain combination of entrances and it would have to continually generate rooms until it satisfys the entrance condition)
- spawning enemies to make the room challenging enough for the player
- additional work throughout the rest of the project to merge changes into our existing room generation and this room generation

I think if we had come across this at the start of the project it would have been worth pursuing, however, I'm not convinced that with 12 days to go it is a good idea to be making major chages. Sorry Stel.

**Comment by kepler471** [comment]
Ok had a chat with Will, and I will go back to the idea of generating levels for development, using this library. So we can have it generate levels for us, and maybe even add some cells to it to improve it. By then saving the scene ( or if that fails, saving an output of the cell positions ), we can generate loads of levels for us to run around in, and slap into the game as templates. 

This would completely remove all the work of combining it with the current level generation.

👍 

I'll keep  this branch up for that purpose.

**Comment by kepler471** [comment]
So have decided that I really like the levels produced by MST, so will take the output from a bunch of those and create some templates.

**Comment by kepler471** [comment]
Work on this shifted to a new PR

**Pull request closed without merging**
