### PR TITLE
(enhancement): Add dodge dash roll

### PR DESCRIPTION
**Pull request by kepler471**

### CODE REVIEW

**Comment by kepler471** [comment]
SHIFT TO DASH

**Comment by kepler471** [comment]
It will need to have a cooldown

**Comment by kepler471** [comment]
Still WIP

**Comment by kepler471** [comment]
Can't dash in different directions

**Comment by Jamesbarford** [comment]
image

then

image

**Comment by kepler471** [comment]
Those errors are fixed. Just plonking on a timer

**Comment by Jamesbarford** [comment]
## questions:
- can he roll off a ledge?
- what happens when you roll between rooms?

**Comment by kepler471** [comment]
> 
> ## questions:
> 
>     * can he roll off a ledge?
> 
>     * what happens when you roll between rooms?

Rolling through rooms seems fine.

Rolling is a linear dash, so off a ledge you just go straight off

**Pull request merged**
