### PR TITLE
Firerate pickups that unlock higher tiers of firerate increases

### PR DESCRIPTION
**Pull request by whitew1994WW**
Large green pulsating blobs to permanently increase themaximum firerate level available

### CODE REVIEW

**Comment by wattsit** [comment]
Are the changes to `SplashScreen.tscn` or `room_base.tscn' needed?

**Comment by whitew1994WW** [comment]
Noo, will revert

**Review by kepler471 — APPROVED** [review]
(⊙_⊙;)

**Comment by kepler471** [comment]
Oh wwait, maybe revert those scenes that Bill mentioned

**Pull request merged**
