### PR TITLE
Chore: File cleanup

### PR DESCRIPTION
**Pull request by wattsit**
Numbers are scary, but not much happening here, mostly just some spring cleaning. Worth doublechecking everything but I don't want to leave this hanging too long.

### CODE REVIEW

**Comment by wattsit** [comment]
Found some issues with dependancies haha. Fixing this now.

**Comment by Jamesbarford** [comment]
@wattsit , let's get the other PR's in before this, I fear we have enough things open that will clash with this. 

What is the reason behind needing to move these things?

**Comment by wattsit** [comment]
@Jamesbarford Only the new health bar #227  currently clashes with this.  And that's an easy fix, HUD.gd just needs to be moved to the HUD folder.

Reason is just a cleanup of files and better organisation. We had a few defunct files and a mess of unrelated scripts and scenes sitting on the top directory.

**Comment by kepler471** [comment]
Cool

**Comment by Jamesbarford** [comment]
> @Jamesbarford Only the new health bar #227 currently clashes with this. And that's an easy fix, HUD.gd just needs to be moved to the HUD folder.
> 
> Reason is just a cleanup of files and better organisation. We had a few defunct files and a mess of unrelated scripts and scenes sitting on the top directory.

Nice one, yeah merge it in!

**Review by Jamesbarford — APPROVED** [review]

**Pull request merged**
